### PR TITLE
Add Dockerfile.arm32v6

### PR DESCRIPTION
**Pull request by toolboc**
Add arm32v6 compatible docker image to support devices like Raspberry Pi 2/3 etc.

### CODE REVIEW

**Comment by linki** [comment]
Thank you @toolboc,

I'm currently building images automatically on `quay.io` which runs on Intel-backed instances, I assume. Can you change the Dockerfile so that it uses an `x86`-compatible image for cross-compiling the binary and then use the `arm` image only in the final step (similar to building for PowerPC: https://github.com/linki/chaoskube/blob/master/Dockerfile.ppc64le)

I'm not an expert in this so please let me know if you have a better idea.

**Comment by linki** [comment]
@toolboc Image build still fails because the `arm` container also executes some commands.

I know it's not optimal but for now I would suggest to just put in the binary and leave out the `chaoskube` user as well as the `dumb-init` stuff (similar to https://github.com/linki/chaoskube/blob/master/Dockerfile.ppc64le).

At least this makes the image build. I think you can still run it as non root by passing a `uid` at runtime (e.g. for powerpc: `docker run -u 2000 quay.io/linki/chaoskube:v0.9.0-ppc64le --version`).

**Comment by toolboc** [comment]
Is this ready for merge now?

**Comment by linki** [comment]
@toolboc Yes! Thanks a lot! Worked fine on my old rpi2 😄

**Comment by linki** [comment]
You can find the arm images here:

```
docker run quay.io/linki/chaoskube:v0.12.0-arm32v6 --help
docker run quay.io/linki/chaoskube:v0.12.0-arm64v8 --help
```

**Pull request merged**
