### PR TITLE
Initial sketch of --exec

### LINKED ISSUE #103: Does chaoskube really kill the pods?
Hi Martin,

I am currently working on a project where we are trying to improve reliability of our software via using chaos engineering (but, unfortunately, have a very little experience with it). Currently, our software runs on Azure/Kubernetes.

We found chaoskube as a promising tool to help us, but we found out, that it's behavior is different than expected. In the description of chaoskube, there is an information that it kills the pods, so I created a hypothesis about what will happen when one of our pods will just be dealing with a request when it is killed (there should be an error response and next requests should be processed by the other pod). When I started the experiment, the pods were killed but no error occured.

Then one of my colleagues looked in the source code of chaoskube and found out, that the pod is not killed (i.e. force killed instantly), but rather terminated (if I got it correctly, then by using this approach, the pod finishes dealing with it's current task and then "dies" peacefuly). 

Is this really how chaoskube works?

We are learning more about chaos every day, but there is a lot of knowledge that we need to gain.

Since my hypothesis was probably wrong, I would be really graceful for any advice about what other chaos experiments is chaoskube suitable for.

Thank You,

Ladislav

### PR DESCRIPTION
**Pull request by jakewins**
This is a proposal to introduce alternative means of killing
pods, outside of simply asking kubernetes to stop them.

Specifically, it allows executing a shell command on a victim
container; that shell command can then be a simple kill -9,
a fork bomb, or any other means of destruction.

There are, at least, two reasons why this is useful. First,
it gives an option of more realistic failures. Simply deleting
a pod is a rather kind way to stop a pod - in reality a pod is likely
to go down in flames from lack of memory, segfaulting or instant
hardware failure. This brings the chaos closer to reality.

The second reason is that this helps test operators that directly
manipulate pods, rather than rely on higher-level concepts like
StatefulSets, Deployments and so on. In this case, the thing we want
to test is the operators ability to realize a pod is severely broken,
and to take appropriate action, depending on what software the operator
is running in the failed pod.

Note: These code changes contain a TODO and no tests; I stopped when I'd verified it worked, so I wouldn't spend more effort than necessary in case this is rejected. If y'all are keen to accept this in some form, I'm super happy to polish it up and add appropriate tests. 

Let me know what you think!

Closes #103

### CODE REVIEW

**Comment by linki** [comment]
@jakewins I'll have a look this week.

**Comment by linki** [comment]
@jakewins sounds like a good idea. How do you want to deal with containers that don't support the command you specify in `--exec`? (e.g. if `kill` isn't available or allowed to exec in the container?)

**Comment by palmerabollo** [comment]
I think that abstracting the chaos action it's a good idea. However, different containers might need different `--exec` commands. Annotating each pod with a `chaoschube/exec-action` would be an option in case you need it (e.g. kill not being available in some containers).

**Comment by linki** [comment]
I merged this PR with master and did my best to make everything compile correctly.

Conflicts mostly included
* the addition of `gracePeriod` which I moved from chaoskube's `New` to the `deletePod` action and 
* creating events which I left in the main chaoskube object

**Pull request merged**
