### PR TITLE
Update client-go to ~4.0.0

### PR DESCRIPTION
**Pull request by linki**
Updates client-go to the latest version to play nice with recent kubernetes versions.

/cc @jinankjain

### CODE REVIEW

**Comment by linki** [comment]
Damn, I messed up the build in the last moment. I'll check back tomorrow.

**Comment by jinankjain** [comment]
It would be good idea to move away from Kingpin and move to more richer cli interface like https://github.com/spf13/cobra

**Comment by linki** [comment]
I'm personally quite happy with kingpin so far. However, I don't mind switching to cobra and would accept PRs for it. What part used in chaoskube do you think is better done with cobra?

**Comment by linki** [comment]
@jinankjain Feel free to open an issue for a switch to cobra if you like.

**Pull request merged**
