### PR TITLE
Single namespace mode

### PR DESCRIPTION
**Pull request by SleepyBrett**
I manage several large multi-tenant clusters, one of our users wanted to use your tool in their namespace so I put together this hack. We only grant our users the ability to get/list/watch pods in their own namespace therefore this tool will error out when it tries to make a cluster-level request for pods.

I made a simple change: If there is only one namespace in the --namespaces arg and that namespace is not negated then it makes the pods query using that namespace as the context.

Thanks!

Closes https://github.com/linki/chaoskube/issues/92

### CODE REVIEW

**Comment by linki** [comment]
@SleepyBrett Thanks a lot!

I'm with you on this. Will take a look.

**Comment by spapinistarkware** [comment]
What's the status on this?

**Comment by stephanecazeaux** [comment]
Hello

@linki any chance to see this PR finalized ?
It brings the solution to a blocking point where ChaosKube cannot be used in multi-tenant environment.

Many thanks.

**Comment by linki** [comment]
This has been added in https://github.com/linki/chaoskube/pull/399 and released in `v0.27.0`. Note, that the approach is slightly different since it uses a special flag but you can achieve the same thing.

I'm closing this now.

**Pull request closed without merging**
