### PR TITLE
Add percentage functionality

### PR DESCRIPTION
**Pull request by klautcomputing**
This is my idea for: https://github.com/linki/chaoskube/issues/20

Changes:
- `chaoskube` now supports the `--percentage` flag
- `--percentage` takes an integer as option
- when using e.g. `--percentage 10` ten percent of the current pods will be killed. `chaoskube` checks after every pod termination how many candidates there are and then calculates how long it will have to wait until it has to terminate another pod so that it reaches `x` percent per hour. This will handle more services getting deploy or old ones removed without having to restart `chaoskube` 
- `chaoskube` needs to be invoked with either `--interval` or `--percentage`, there is no default anymore

Let me know what you think.

I removed `log.Debugf("Sleeping for %s...", interval)` because we are technically not sleeping anymore. And I only inform about interval updates. Feel free to ask me to bring that functionality back if you want it to stay.

### CODE REVIEW

**Comment by klautcomputing** [comment]
Oh yeah, I didn't write tests... yet. Let me know if you want this to be merged into master and I will write tests for it.

**Comment by linki** [comment]
@klautcomputing Thanks for your work. I would be happy to merge this to `master` once you add the tests.

**Comment by klautcomputing** [comment]
You are welcome. I will do so either today or tomorrow.

**Comment by klautcomputing** [comment]
this is not needed anymore see #47 for a better approach

**Pull request closed without merging**
