### PR TITLE
Add support to configure times to suspend chaos.

### PR DESCRIPTION
**Pull request by twildeboer**
This implements the feature as briefly discussed in #48 with some minor name changes.
Please Note:
* I made an assumption on the version number changes: `0.6.2`
* Addition of a helm chart example
* Dockerfile change required to include TZ database

This has been tested in our environment and appears to work as advertised.

### CODE REVIEW

**Comment by linki** [comment]
@twildeboer Thanks, I'll try to look at this as soon as I can and compare it to @klautcomputing's version. For the sake of a small PR can you split out the chart related stuff in a separate PR?

**Comment by klautcomputing** [comment]
FYI: I don't think my code is mergeable as is and I don't intend to put more time into it. @linki

**Comment by twildeboer** [comment]
@linki - Will do.

**Comment by twildeboer** [comment]
Breaking this up into two PRs as requested.

**Pull request closed without merging**
